In [104]:
import pandas as pd
import numpy as np

In [105]:
path = r"C:\Users\sonik\Desktop\Coding Cloud\Lectures\Movieratingdata1.csv"

In [106]:
df = pd.read_csv(path)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [107]:
df = pd.read_csv(path, na_values = {'not available', 'not mension',})

df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014.0,NaN,NaN
3,4,1390411,NaN,2015.0,NaN,5.0
4,5,6306064,NaN,NaN,Action|Adventure|Biography|Drama|Romance|Thriller,4.0
5,6,6306064,NaN,NaN,Action|Adventure|Biography|Drama|Romance|Thriller,5.0
6,7,2719848,NaN,2015.0,Action|Adventure|Biography|Drama|Thriller,NaN
7,8,462504,NaN,2006.0,Action|Adventure|Biography|Drama|War,NaN
8,9,NaN,NaN,2020.0,Action|Adventure|Biography|Drama|Western,10.0
9,10,163225,The Revenant,2015.0,Action|Adventure|Biography|Drama|Western,9.0
10,11,1663202,NaN,2015.0,Action|Adventure|Biography|Drama|Western,9.0
11,12,1663202,The Revenant,2021.0,Action|Adventure|Biography|Drama|Western,6.0

In [108]:
df = pd.read_csv(path, na_values = {'not available', 'not mension'})

df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014.0,NaN,NaN
3,4,1390411,NaN,2015.0,NaN,5.0
4,5,6306064,NaN,NaN,Action|Adventure|Biography|Drama|Romance|Thriller,4.0
5,6,6306064,NaN,NaN,Action|Adventure|Biography|Drama|Romance|Thriller,5.0
6,7,2719848,NaN,2015.0,Action|Adventure|Biography|Drama|Thriller,NaN
7,8,462504,NaN,2006.0,Action|Adventure|Biography|Drama|War,NaN
8,9,NaN,NaN,2020.0,Action|Adventure|Biography|Drama|Western,10.0
9,10,163225,The Revenant,2015.0,Action|Adventure|Biography|Drama|Western,9.0
10,11,1663202,NaN,2015.0,Action|Adventure|Biography|Drama|Western,9.0
11,12,1663202,The Revenant,2021.0,Action|Adventure|Biography|Drama|Western,6.0

In [109]:
df = pd.read_csv(path, na_values = {'PRODUCTION YEAR' : 'not available','RATING':'not mension'})

df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,NaN
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [110]:
df = pd.read_csv(path, na_values = {'not available', 'not mension',})

df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015.0,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014.0,NaN,NaN
3,4,1390411,NaN,2015.0,NaN,5.0
4,5,6306064,NaN,NaN,Action|Adventure|Biography|Drama|Romance|Thriller,4.0
5,6,6306064,NaN,NaN,Action|Adventure|Biography|Drama|Romance|Thriller,5.0
6,7,2719848,NaN,2015.0,Action|Adventure|Biography|Drama|Thriller,NaN
7,8,462504,NaN,2006.0,Action|Adventure|Biography|Drama|War,NaN
8,9,NaN,NaN,2020.0,Action|Adventure|Biography|Drama|Western,10.0
9,10,163225,The Revenant,2015.0,Action|Adventure|Biography|Drama|Western,9.0
10,11,1663202,NaN,2015.0,Action|Adventure|Biography|Drama|Western,9.0
11,12,1663202,The Revenant,2021.0,Action|Adventure|Biography|Drama|Western,6.0

In [111]:
df = pd.read_csv(path, keep_default_na = True)

df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [112]:
df.replace(to_replace = 'not available', value = None, inplace=True)
df.replace(to_replace= 'not mension', value = None, inplace=True)
df.replace('not value', np.nan, inplace=True)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,None,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,None,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,None
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,None
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [113]:
df.replace('1390411','krish', inplace=True)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,2014,NaN,NaN
3,4,krish,NaN,2015,NaN,5
4,5,6306064,NaN,None,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,None,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,None
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,None
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [114]:
df.dtypes

USER_ID             int64
MOVIE_ID           object
MOVIE_TITLE        object
PRODUCTION_YEAR    object
GENRES             object
RATING             object
dtype: object

In [115]:
df.replace(1,12,inplace=True)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,12,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,2014,NaN,NaN
3,4,krish,NaN,2015,NaN,5
4,5,6306064,NaN,None,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,None,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,None
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,None
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [116]:
df = pd.read_csv(path)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [117]:
df.isnull().sum()

USER_ID            0
MOVIE_ID           2
MOVIE_TITLE        9
PRODUCTION_YEAR    1
GENRES             3
RATING             3
dtype: int64

In [118]:
df.isnull().sum().sum()

np.int64(18)

In [119]:
df.isnull().sum()*100/12

USER_ID             0.000000
MOVIE_ID           16.666667
MOVIE_TITLE        75.000000
PRODUCTION_YEAR     8.333333
GENRES             25.000000
RATING             25.000000
dtype: float64

In [120]:
df.isnull().sum()*100/(df.shape[0])

USER_ID             0.000000
MOVIE_ID           16.666667
MOVIE_TITLE        75.000000
PRODUCTION_YEAR     8.333333
GENRES             25.000000
RATING             25.000000
dtype: float64

In [121]:
#*******
df.dropna()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [122]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [123]:
df.dropna(axis=1)

    USER_ID
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9
9        10
10       11
11       12

In [124]:
df.dropna(how='any')

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [125]:
df.dropna(how='all')

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [126]:
df.dropna(axis=0)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [127]:
df.dropna(subset={"GENRES"})

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [128]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [130]:
df.drop(columns='MOVIE_TITLE',inplace=True)
df

KeyError: "['MOVIE_TITLE'] not found in axis"

In [133]:
df = pd.read_csv(path)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [136]:
df.fillna(5)

#by default inplace=True applied.

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,5
1,2,5,5,5,5,5
2,3,not value,5,2014,5,5
3,4,1390411,5,2015,5,5
4,5,6306064,5,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,5,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,5,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,5,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,5,5,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,5,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [141]:
df.fillna({'MOVIE_TITLE' : 'BAITMAN', 'RATING' : 6})

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,6
1,2,NaN,BAITMAN,NaN,NaN,6
2,3,not value,BAITMAN,2014,NaN,6
3,4,1390411,BAITMAN,2015,NaN,5
4,5,6306064,BAITMAN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,BAITMAN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,BAITMAN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,BAITMAN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,BAITMAN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,BAITMAN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [143]:
df.fillna(method='ffill')

C:\Users\sonik\AppData\Local\Temp\ipykernel_18144\253117906.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,4642044,Riot,2015,Action,NaN
2,3,not value,Riot,2014,Action,NaN
3,4,1390411,Riot,2015,Action,5
4,5,6306064,Riot,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,Riot,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,Riot,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,Riot,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,462504,Riot,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [146]:
df.fillna(method='ffill',limit=2)

C:\Users\sonik\AppData\Local\Temp\ipykernel_18144\2005079682.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',limit=2)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,4642044,Riot,2015,Action,NaN
2,3,not value,Riot,2014,Action,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,462504,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [149]:
df.fillna(method='bfill')

C:\Users\sonik\AppData\Local\Temp\ipykernel_18144\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,5
1,2,not value,The Revenant,2014,Action|Adventure|Biography|Drama|Romance|Thriller,5
2,3,not value,The Revenant,2014,Action|Adventure|Biography|Drama|Romance|Thriller,5
3,4,1390411,The Revenant,2015,Action|Adventure|Biography|Drama|Romance|Thriller,5
4,5,6306064,The Revenant,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,The Revenant,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,The Revenant,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,The Revenant,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,163225,The Revenant,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [151]:
df.fillna(method='bfill',limit=3)

C:\Users\sonik\AppData\Local\Temp\ipykernel_18144\3828626142.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill',limit=3)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,5
1,2,not value,NaN,2014,Action|Adventure|Biography|Drama|Romance|Thriller,5
2,3,not value,NaN,2014,Action|Adventure|Biography|Drama|Romance|Thriller,5
3,4,1390411,NaN,2015,Action|Adventure|Biography|Drama|Romance|Thriller,5
4,5,6306064,NaN,not available,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,The Revenant,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,The Revenant,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,163225,The Revenant,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

In [34]:
import pandas as pd
import numpy as np

In [35]:
path = r"C:\Users\sonik\Desktop\Coding Cloud\Sample .CSV Data Files\Movieratingdata4.csv"

In [36]:
df = pd.read_csv(path)

df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      NaN   4642044              NaN     NaN     NaN
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      NaN   1390411           2015.0     NaN     6.0
4  25-05-2021      NaN   6306064              NaN       B     NaN
5  25-06-2021      NaN   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     NaN
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [37]:
df.interpolate()

C:\Users\sonik\AppData\Local\Temp\ipykernel_10564\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      2.0   4642044           2014.5     NaN     9.0
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      4.0   1390411           2015.0     NaN     6.0
4  25-05-2021      5.0   6306064           2017.5       B     5.0
5  25-06-2021      6.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     9.0
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [38]:
df.interpolate(method='linear')

C:\Users\sonik\AppData\Local\Temp\ipykernel_10564\1601761006.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear')

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      2.0   4642044           2014.5     NaN     9.0
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      4.0   1390411           2015.0     NaN     6.0
4  25-05-2021      5.0   6306064           2017.5       B     5.0
5  25-06-2021      6.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     9.0
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [39]:
df = pd.read_csv(r"C:\Users\sonik\Desktop\Coding Cloud\Sample .CSV Data Files\Movieratingdata4.csv",parse_dates=["DATE"])
df
df.dtypes

C:\Users\sonik\AppData\Local\Temp\ipykernel_10564\1127117036.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv(r"C:\Users\sonik\Desktop\Coding Cloud\Sample .CSV Data Files\Movieratingdata4.csv",parse_dates=["DATE"])

DATE               datetime64[ns]
USER_ID                   float64
MOVIE_ID                    int64
PRODUCTION_YEAR           float64
Section                    object
RATING                    float64
dtype: object

In [40]:
df.set_index("DATE",inplace=True)

df

            USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
DATE
2021-01-25      1.0   4642044           2015.0       A    10.0
2021-02-25      NaN   4642044              NaN     NaN     NaN
2021-03-25      3.0   1245897           2014.0     NaN     8.0
2021-04-25      NaN   1390411           2015.0     NaN     6.0
2021-05-25      NaN   6306064              NaN       B     NaN
2021-06-25      NaN   6306064           2020.0       D     4.0
2021-07-25      7.0   2719848           2015.0       E     4.0
2021-08-25      8.0    462504           2006.0       B     9.0
2021-09-25      9.0     25468           2015.0       F     NaN
2021-10-25     10.0   2564789           2015.0       D     9.0

In [41]:
df.interpolate(method='time')

C:\Users\sonik\AppData\Local\Temp\ipykernel_10564\722817345.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='time')

              USER_ID  MOVIE_ID  PRODUCTION_YEAR Section     RATING
DATE
2021-01-25   1.000000   4642044      2015.000000       A  10.000000
2021-02-25   2.050847   4642044      2014.474576     NaN   8.949153
2021-03-25   3.000000   1245897      2014.000000     NaN   8.000000
2021-04-25   4.016393   1390411      2015.000000     NaN   6.000000
2021-05-25   5.000000   6306064      2017.459016       B   5.016393
2021-06-25   6.016393   6306064      2020.000000       D   4.000000
2021-07-25   7.000000   2719848      2015.000000       E   4.000000
2021-08-25   8.000000    462504      2006.000000       B   9.000000
2021-09-25   9.000000     25468      2015.000000       F   9.000000
2021-10-25  10.000000   2564789      2015.000000       D   9.000000

In [42]:
df = pd.read_csv(r"C:\Users\sonik\Desktop\Coding Cloud\Sample .CSV Data Files\Movieratingdata4.csv", index_col=['MOVIE_ID'])
df

                DATE  USER_ID  PRODUCTION_YEAR Section  RATING
MOVIE_ID
4642044   25-01-2021      1.0           2015.0       A    10.0
4642044   25-02-2021      NaN              NaN     NaN     NaN
1245897   25-03-2021      3.0           2014.0     NaN     8.0
1390411   25-04-2021      NaN           2015.0     NaN     6.0
6306064   25-05-2021      NaN              NaN       B     NaN
6306064   25-06-2021      NaN           2020.0       D     4.0
2719848   25-07-2021      7.0           2015.0       E     4.0
462504    25-08-2021      8.0           2006.0       B     9.0
25468     25-09-2021      9.0           2015.0       F     NaN
2564789   25-10-2021     10.0           2015.0       D     9.0

In [43]:
df.interpolate(method='index')

C:\Users\sonik\AppData\Local\Temp\ipykernel_10564\2515484856.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='index')

                DATE    USER_ID  PRODUCTION_YEAR Section  RATING
MOVIE_ID
4642044   25-01-2021   1.000000           2015.0       A    10.0
4642044   25-02-2021   1.000000           2015.0     NaN    10.0
1245897   25-03-2021   3.000000           2014.0     NaN     8.0
1390411   25-04-2021   3.767006           2015.0     NaN     6.0
6306064   25-05-2021   1.000000           2020.0       B     4.0
6306064   25-06-2021   1.000000           2020.0       D     4.0
2719848   25-07-2021   7.000000           2015.0       E     4.0
462504    25-08-2021   8.000000           2006.0       B     9.0
25468     25-09-2021   9.000000           2015.0       F     9.0
2564789   25-10-2021  10.000000           2015.0       D     9.0

In [44]:
df.interpolate(method='nearest')

C:\Users\sonik\AppData\Local\Temp\ipykernel_10564\1654062127.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='nearest')

ImportError: Missing optional dependency 'scipy'. nearest interpolation requires SciPy. Use pip or conda to install scipy.

In [45]:
df.interpolate(limit=1)

C:\Users\sonik\AppData\Local\Temp\ipykernel_10564\1270544217.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit=1)

                DATE  USER_ID  PRODUCTION_YEAR Section  RATING
MOVIE_ID
4642044   25-01-2021      1.0           2015.0       A    10.0
4642044   25-02-2021      2.0           2014.5     NaN     9.0
1245897   25-03-2021      3.0           2014.0     NaN     8.0
1390411   25-04-2021      4.0           2015.0     NaN     6.0
6306064   25-05-2021      NaN           2017.5       B     5.0
6306064   25-06-2021      NaN           2020.0       D     4.0
2719848   25-07-2021      7.0           2015.0       E     4.0
462504    25-08-2021      8.0           2006.0       B     9.0
25468     25-09-2021      9.0           2015.0       F     9.0
2564789   25-10-2021     10.0           2015.0       D     9.0

In [46]:
df.interpolate(limit_direction='backward',limit=3)

C:\Users\sonik\AppData\Local\Temp\ipykernel_10564\738198474.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit_direction='backward',limit=3)

                DATE  USER_ID  PRODUCTION_YEAR Section  RATING
MOVIE_ID
4642044   25-01-2021      1.0           2015.0       A    10.0
4642044   25-02-2021      2.0           2014.5     NaN     9.0
1245897   25-03-2021      3.0           2014.0     NaN     8.0
1390411   25-04-2021      4.0           2015.0     NaN     6.0
6306064   25-05-2021      5.0           2017.5       B     5.0
6306064   25-06-2021      6.0           2020.0       D     4.0
2719848   25-07-2021      7.0           2015.0       E     4.0
462504    25-08-2021      8.0           2006.0       B     9.0
25468     25-09-2021      9.0           2015.0       F     9.0
2564789   25-10-2021     10.0           2015.0       D     9.0