In [30]:
import pandas as pd
import numpy as np

In [31]:
people= {
    "First" : ['krish', 'priyraj', 'dhyeyraj'],
    "Last" : ['soni', 'jadeja', 'parmar'],
    "email" : ['krishsoni@gmail.com', 'priryaj@gamil.colm', 'djjadeja@gmail.com']
}

In [ ]:
df = pd.DataFrame(people)
df

      First    Last                email
0     krish    soni  krishsoni@gmail.com
1   priyraj  jadeja   priryaj@gamil.colm
2  dhyeyraj  parmar   djjadeja@gmail.com

In [ ]:
df['Fullname'] = df['First'] + ' ' +df['Last']
df

      First    Last                email         Fullname
0     krish    soni  krishsoni@gmail.com       krish soni
1   priyraj  jadeja   priryaj@gamil.colm   priyraj jadeja
2  dhyeyraj  parmar   djjadeja@gmail.com  dhyeyraj parmar

In [34]:
df.drop(columns=['First','Last'], inplace= True)
df

                 email         Fullname
0  krishsoni@gmail.com       krish soni
1   priryaj@gamil.colm   priyraj jadeja
2   djjadeja@gmail.com  dhyeyraj parmar

In [35]:
df[['First', 'Last']] = df['Fullname'].str.split(" ",expand=True)

df

                 email         Fullname     First    Last
0  krishsoni@gmail.com       krish soni     krish    soni
1   priryaj@gamil.colm   priyraj jadeja   priyraj  jadeja
2   djjadeja@gmail.com  dhyeyraj parmar  dhyeyraj  parmar

In [36]:
x = df.pop('Fullname')

x

0         krish soni
1     priyraj jadeja
2    dhyeyraj parmar
Name: Fullname, dtype: object

In [37]:
df.insert(0,'Fullname', x)

df

          Fullname                email     First    Last
0       krish soni  krishsoni@gmail.com     krish    soni
1   priyraj jadeja   priryaj@gamil.colm   priyraj  jadeja
2  dhyeyraj parmar   djjadeja@gmail.com  dhyeyraj  parmar

In [38]:
# if want raw index use replace

In [39]:
df1 = pd.DataFrame ({'Fruit' : ['banana', 'apple','orange', 'grape'], 'Wholesaler' : [100, 40 ,80, 60], 'market': [100,80,40,60]})

df1

    Fruit  Wholesaler  market
0  banana         100     100
1   apple          40      80
2  orange          80      40
3   grape          60      60

In [40]:
#merge two dataset with how

#--> method 

#left  --   Use keys from left object
#right --   Use keys from right object
#outer --   Use union of keys
#inner --   Use iintersection of keys

In [41]:
df2 = pd.DataFrame ({'Fruit' : ['apple', 'banana', 'grape', 'kiwi'], 'Wholesaler' : [60,20,45,100]})
df2

    Fruit  Wholesaler
0   apple          60
1  banana          20
2   grape          45
3    kiwi         100

In [42]:
pd.merge(df1,df2, how='inner', on = 'Fruit')

    Fruit  Wholesaler_x  market  Wholesaler_y
0  banana           100     100            20
1   apple            40      80            60
2   grape            60      60            45

In [43]:
pd.merge(df1,df2, how='left', on='Fruit')

    Fruit  Wholesaler_x  market  Wholesaler_y
0  banana           100     100          20.0
1   apple            40      80          60.0
2  orange            80      40           NaN
3   grape            60      60          45.0

In [44]:
pd.merge(df1,df2, how='outer', on='Fruit' )

    Fruit  Wholesaler_x  market  Wholesaler_y
0   apple          40.0    80.0          60.0
1  banana         100.0   100.0          20.0
2   grape          60.0    60.0          45.0
3    kiwi           NaN     NaN         100.0
4  orange          80.0    40.0           NaN

In [58]:
df3 = pd.DataFrame({'ID' : [1,2,3,4], 'Name' : ['a','b','c', 'd']})

df3

   ID Name
0   1    a
1   2    b
2   3    c
3   4    d

In [59]:
df4 = pd.DataFrame({'ID' : [5,6,7,8], 'Name' : ['a','b','c', 'd']})

df4

   ID Name
0   5    a
1   6    b
2   7    c
3   8    d

In [60]:
pd.merge(df3,df4, left_index=True, right_index=True) #Use Left & right indexes together

   ID_x Name_x  ID_y Name_y
0     1      a     5      a
1     2      b     6      b
2     3      c     7      c
3     4      d     8      d

In [62]:
pd.merge(df3,df4, left_index=True, right_index=True,suffixes=['priyraj','krish'])

   IDpriyraj Namepriyraj  IDkrish Namekrish
0          1           a        5         a
1          2           b        6         b
2          3           c        7         c
3          4           d        8         d

In [ ]:
people = {
    "First" : ['hardik', 'harshil','dharuv'],
    "Last"  : ['kher', 'vaghela', 'giri'],
}

In [68]:
people1 = {
    "First" : ['ram', 'shayam', 'shiv'],
    "Last"  : ['kher', 'vaghela', 'giri']
}

In [71]:
df1 = pd.DataFrame(people)
df1

   First    Last
0  krish  parmar
1  priya    soni
2     dj   gohil

In [73]:
df2 = pd.DataFrame(people1)

df2

    First     Last
0     ram     kher
1  shayam  vaghela
2    shiv     giri

In [76]:
df3 = pd.concat([df1,df2])

df3

    First     Last
0   krish   parmar
1   priya     soni
2      dj    gohil
0     ram     kher
1  shayam  vaghela
2    shiv     giri

In [81]:
df4 = pd.concat([df1,df2], axis = 1)

df4

   First    Last   First     Last
0  krish  parmar     ram     kher
1  priya    soni  shayam  vaghela
2     dj   gohil    shiv     giri

In [84]:
df3 = pd.concat([df1,df2], axis = 0, ignore_index=True)

df3

    First     Last
0   krish   parmar
1   priya     soni
2      dj    gohil
3     ram     kher
4  shayam  vaghela
5    shiv     giri

In [87]:
df3 = pd.concat([df1,df2],axis = 1, ignore_index=True)

df3

       0       1       2        3
0  krish  parmar     ram     kher
1  priya    soni  shayam  vaghela
2     dj   gohil    shiv     giri