

# CSV file:
--> Comma Separated Values 
--> Universaly Use 
--> Easy to Understand
--> Quick to Create

In [2]:
import pandas as pd

In [6]:
path = r"C:\Users\Sandeep\python lerning\Dataset\Movieratingdata.csv"
#path = "C:\\Users\\Helly\\Desktop\\DATA\\2. Python libraries\\2) Pandas\\Dataset\\Movieratingdata.csv"

# Site for DataSet "https://www.kaggle.com"

# Read csv file

In [7]:
df = pd.read_csv(path)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

# columns name

In [8]:
df.columns

Index(['USER_ID', 'MOVIE_ID', 'MOVIE_TITLE', 'PRODUCTION_YEAR', 'GENRES',
       'RATING', 'Unnamed: 6', 'Unnamed: 7', 'GENRES.1', 'Unnamed: 9'],
      dtype='object')

# find datatype

In [9]:
df.dtypes

USER_ID              int64
MOVIE_ID             int64
MOVIE_TITLE         object
PRODUCTION_YEAR      int64
GENRES              object
RATING             float64
Unnamed: 6         float64
Unnamed: 7         float64
GENRES.1            object
Unnamed: 9         float64
dtype: object

# change datatype

In [10]:
df["USER_ID"] = df["USER_ID"].astype(float)

In [11]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1.0,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2.0,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3.0,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4.0,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5.0,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496.0,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497.0,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498.0,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499.0,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500.0,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [12]:
df.dtypes

USER_ID            float64
MOVIE_ID             int64
MOVIE_TITLE         object
PRODUCTION_YEAR      int64
GENRES              object
RATING             float64
Unnamed: 6         float64
Unnamed: 7         float64
GENRES.1            object
Unnamed: 9         float64
dtype: object

In [13]:
df = pd.read_csv(path,dtype={"MOVIE_ID":"float64","PRODUCTION_YEAR":"float64","USER_ID":"float64"})
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1.0,4642044.0,Riot,2015.0,Action,8.0,NaN,1.0,action,8.0
1,2.0,1925518.0,The Protector 2,2013.0,Action,5.0,NaN,5.0,suspense,6.0
2,3.0,372784.0,Batman Begins,2005.0,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4.0,1390411.0,In the Heart of the Sea,2015.0,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5.0,6306064.0,Adrift,2018.0,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496.0,1846589.0,Hunter Killer,2018.0,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497.0,4196776.0,Jason Bourne,2016.0,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498.0,7456310.0,Anna,2019.0,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499.0,8106534.0,6 Underground,2019.0,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500.0,2302755.0,Olympus Has Fallen,2013.0,Action|Thriller,1.0,NaN,NaN,NaN,NaN

# nrow , skiprows and usecols while csv reading

In [1]:
# nrow
df = pd.read_csv(path,nrows=5)
df

NameError: name 'pd' is not defined

In [15]:
# skiprows
df = pd.read_csv(path,skiprows=5)
df

,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4,Unnamed: 6,Unnamed: 7,adventures,Unnamed: 9
0,6,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5.0,NaN,NaN,NaN,NaN
1,7,2719848,Everest,2015,Action|Adventure|Biography|Drama|Thriller,6.0,NaN,NaN,NaN,NaN
2,8,462504,Rescue Dawn,2006,Action|Adventure|Biography|Drama|War,8.0,NaN,NaN,NaN,NaN
3,9,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,10.0,NaN,NaN,NaN,NaN
4,10,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
490,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
491,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
492,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
493,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
494,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [12]:
df = pd.read_csv(path,skiprows=[1,3,7,10,11])
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,2,1925518,The Protector 2,2013,Action,5,NaN,5.0,suspense,6.0
1,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5,NaN,NaN,thriller,4.0
2,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4,NaN,NaN,adventures,NaN
3,6,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5,NaN,NaN,NaN,NaN
4,8,462504,Rescue Dawn,2006,Action|Adventure|Biography|Drama|War,8,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
490,496,1846589,Hunter Killer,2018,Action|Thriller,6,NaN,NaN,NaN,NaN
491,497,4196776,Jason Bourne,2016,Action|Thriller,6,NaN,NaN,NaN,NaN
492,498,7456310,Anna,2019,Action|Thriller,7,NaN,NaN,NaN,NaN
493,499,8106534,6 Underground,2019,Action|Thriller,4,NaN,NaN,NaN,NaN
494,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1,NaN,NaN,NaN,NaN

In [13]:
# usecols
df = pd.read_csv(path,usecols=["MOVIE_TITLE"])
df

                  MOVIE_TITLE
0                       Riot
1            The Protector 2
2              Batman Begins
3    In the Heart of the Sea
4                     Adrift
..                        ...
495            Hunter Killer
496             Jason Bourne
497                     Anna
498            6 Underground
499       Olympus Has Fallen

[500 rows x 1 columns]

In [14]:
df = pd.read_csv(path,usecols=["MOVIE_TITLE","PRODUCTION_YEAR","RATING","GENRES"])
df

,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,Riot,2015,Action,8.0
1,The Protector 2,2013,Action,5.0
2,Batman Begins,2005,Action|Adventure,9.0
3,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0
4,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0
...,...,...,...,...
495,Hunter Killer,2018,Action|Thriller,6.0
496,Jason Bourne,2016,Action|Thriller,6.0
497,Anna,2019,Action|Thriller,7.0
498,6 Underground,2019,Action|Thriller,4.0
499,Olympus Has Fallen,2013,Action|Thriller,1.0

In [15]:
df = pd.read_csv(path,usecols=[0,3,5])
df

     USER_ID  PRODUCTION_YEAR  RATING
0          1             2015     8.0
1          2             2013     5.0
2          3             2005     9.0
3          4             2015     5.0
4          5             2018     4.0
..       ...              ...     ...
495      496             2018     6.0
496      497             2016     6.0
497      498             2019     7.0
498      499             2019     4.0
499      500             2013     1.0

[500 rows x 3 columns]

# set column as index one or more

In [63]:
df = pd.read_csv(path,index_col=["USER_ID"])
df

,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
USER_ID,,,,,,,,,
1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...
496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [64]:
df.columns

Index(['MOVIE_ID', 'MOVIE_TITLE', 'PRODUCTION_YEAR', 'GENRES', 'RATING',
       'Unnamed: 6', 'Unnamed: 7', 'GENRES.1', 'Unnamed: 9'],
      dtype='object')

In [17]:
df = pd.read_csv(path,index_col=["MOVIE_TITLE","USER_ID"])
df

,,MOVIE_ID,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
MOVIE_TITLE,USER_ID,,,,,,,,
Riot,1,4642044,2015,Action,8.0,NaN,1.0,action,8.0
The Protector 2,2,1925518,2013,Action,5.0,NaN,5.0,suspense,6.0
Batman Begins,3,372784,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
In the Heart of the Sea,4,1390411,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
Adrift,5,6306064,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...
Hunter Killer,496,1846589,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
Jason Bourne,497,4196776,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
Anna,498,7456310,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
6 Underground,499,8106534,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
Olympus Has Fallen,500,2302755,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [65]:
df = pd.read_csv(path,index_col=[0,1,2,3])
df

,,,,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,,,,,,
1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...
496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [19]:
# reset column index with example of missing index

In [66]:
df.reset_index(inplace=True)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

# sort index

In [67]:
df = pd.read_csv(path,index_col=["PRODUCTION_YEAR"])
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
PRODUCTION_YEAR,,,,,,,,,
2015,1,4642044,Riot,Action,8.0,NaN,1.0,action,8.0
2013,2,1925518,The Protector 2,Action,5.0,NaN,5.0,suspense,6.0
2005,3,372784,Batman Begins,Action|Adventure,9.0,NaN,NaN,drama,5.0
2015,4,1390411,In the Heart of the Sea,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
2018,5,6306064,Adrift,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...
2018,496,1846589,Hunter Killer,Action|Thriller,6.0,NaN,NaN,NaN,NaN
2016,497,4196776,Jason Bourne,Action|Thriller,6.0,NaN,NaN,NaN,NaN
2019,498,7456310,Anna,Action|Thriller,7.0,NaN,NaN,NaN,NaN
2019,499,8106534,6 Underground,Action|Thriller,4.0,NaN,NaN,NaN,NaN
2013,500,2302755,Olympus Has Fallen,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [68]:
df.sort_index()

,USER_ID,MOVIE_ID,MOVIE_TITLE,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
PRODUCTION_YEAR,,,,,,,,,
1967,255,61418,Bonnie and Clyde,Action|Biography|Crime|Drama,8.0,NaN,NaN,NaN,NaN
1969,236,64757,On Her Majesty's Secret Service,Action|Adventure|Thriller,7.0,NaN,NaN,NaN,NaN
1972,365,69121,Prime Cut,Action|Crime|Drama|Thriller,8.0,NaN,NaN,NaN,NaN
1973,484,70909,Westworld,Action|Sci-Fi|Thriller|Western,7.0,NaN,NaN,NaN,NaN
1974,237,71807,The Man with the Golden Gun,Action|Adventure|Thriller,7.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2019,206,4154664,Captain Marvel,Action|Adventure|Sci-Fi,7.0,NaN,NaN,NaN,NaN
2019,208,6565702,Dark Phoenix,Action|Adventure|Sci-Fi,6.0,NaN,NaN,NaN,NaN
2019,211,4154664,Captain Marvel,Action|Adventure|Sci-Fi,7.0,NaN,NaN,NaN,NaN
2019,156,6565702,Dark Phoenix,Action|Adventure|Sci-Fi,5.0,NaN,NaN,NaN,NaN
2019,142,5886046,Escape Room,Action|Adventure|Horror|Mystery|Thriller,7.0,NaN,NaN,NaN,NaN

In [70]:
df.sort_index(ascending=False,inplace=True)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
PRODUCTION_YEAR,,,,,,,,,
2019,142,5886046,Escape Room,Action|Adventure|Horror|Mystery|Thriller,7.0,NaN,NaN,NaN,NaN
2019,208,6565702,Dark Phoenix,Action|Adventure|Sci-Fi,6.0,NaN,NaN,NaN,NaN
2019,30,448115,Shazam!,Action|Adventure|Comedy|Fantasy,10.0,NaN,NaN,NaN,NaN
2019,426,1025100,Gemini Man,Action|Drama|Sci-Fi|Thriller,4.0,NaN,NaN,NaN,NaN
2019,33,448115,Shazam!,Action|Adventure|Comedy|Fantasy,8.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1974,237,71807,The Man with the Golden Gun,Action|Adventure|Thriller,7.0,NaN,NaN,NaN,NaN
1973,484,70909,Westworld,Action|Sci-Fi|Thriller|Western,7.0,NaN,NaN,NaN,NaN
1972,365,69121,Prime Cut,Action|Crime|Drama|Thriller,8.0,NaN,NaN,NaN,NaN
1969,236,64757,On Her Majesty's Secret Service,Action|Adventure|Thriller,7.0,NaN,NaN,NaN,NaN
1967,255,61418,Bonnie and Clyde,Action|Biography|Crime|Drama,8.0,NaN,NaN,NaN,NaN

# header

In [72]:
df = pd.read_csv(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/2) Pandas/Dataset/Movieratingdata5.csv")
df

,1,2,3,4,5,6,7,8,9,10
0,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,NaN,NaN,GENRES,NaN
1,1,4642044,Riot,2015,Action,8,NaN,1.0,action,8.0
2,2,1925518,The Protector 2,2013,Action,5,NaN,5.0,suspense,6.0
3,3,372784,Batman Begins,2005,Action|Adventure,9,NaN,NaN,drama,5.0
4,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5,NaN,NaN,thriller,4.0
...,...,...,...,...,...,...,...,...,...,...
496,496,1846589,Hunter Killer,2018,Action|Thriller,6,NaN,NaN,NaN,NaN
497,497,4196776,Jason Bourne,2016,Action|Thriller,6,NaN,NaN,NaN,NaN
498,498,7456310,Anna,2019,Action|Thriller,7,NaN,NaN,NaN,NaN
499,499,8106534,6 Underground,2019,Action|Thriller,4,NaN,NaN,NaN,NaN
500,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1,NaN,NaN,NaN,NaN

In [76]:
df = pd.read_csv(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/2) Pandas/Dataset/Movieratingdata5.csv",header=1)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [26]:
df1 = pd.read_csv(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/2) Pandas/Dataset/Movieratingdata6.csv")
df1

,1,4642044,Riot,2015,Action,8,Unnamed: 6,1.1,action,8.1
0,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
1,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
2,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
3,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
4,6,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
494,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
495,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
497,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
498,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [78]:
df1 = pd.read_csv(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/2) Pandas/Dataset/Movieratingdata6.csv",header=None)
df1

,0,1,2,3,4,5,6,7,8,9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [28]:
df1 = pd.read_csv(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/2) Pandas/Dataset/Movieratingdata6.csv", header=None)
df1 = df1.add_prefix("Data")

C:\Users\baps\AppData\Local\Temp\ipykernel_4668\3412988388.py:1: FutureWarning: The prefix argument has been deprecated and will be removed in a future version. Use a list comprehension on the column names in the future.


  df1 = pd.read_csv(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/2) Pandas/Dataset/Movieratingdata6.csv",header=None,prefix="Data")

,Data0,Data1,Data2,Data3,Data4,Data5,Data6,Data7,Data8,Data9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [29]:
df1 = pd.read_csv(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/2) Pandas/Dataset/Movieratingdata6.csv",names=["A","B","C","D","E","F","G","H","I","J"])
df1

,A,B,C,D,E,F,G,H,I,J
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

# head and tail

In [79]:
df = pd.read_csv(path)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [84]:
df.head()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN

In [32]:
df.head(10)       #max is 60

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
5,6,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5.0,NaN,NaN,NaN,NaN
6,7,2719848,Everest,2015,Action|Adventure|Biography|Drama|Thriller,6.0,NaN,NaN,NaN,NaN
7,8,462504,Rescue Dawn,2006,Action|Adventure|Biography|Drama|War,8.0,NaN,NaN,NaN,NaN
8,9,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,10.0,NaN,NaN,NaN,NaN
9,10,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9.0,NaN,NaN,NaN,NaN

In [33]:
df.tail()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [34]:
df.tail(7)     #max is 60

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
493,494,1606378,A Good Day to Die Hard,2013,Action|Thriller,5.0,NaN,NaN,NaN,NaN
494,495,1781922,No Escape,2015,Action|Thriller,7.0,NaN,NaN,NaN,NaN
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

# info,describe,shape(with its option),size,sample

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   USER_ID          500 non-null    int64
 1   MOVIE_ID         500 non-null    int64
 2   MOVIE_TITLE      500 non-null    object
 3   PRODUCTION_YEAR  500 non-null    int64
 4   GENRES           500 non-null    object
 5   RATING           500 non-null    float64
 6   Unnamed: 6       0 non-null      float64
 7   Unnamed: 7       2 non-null      float64
 8   GENRES.1         5 non-null      object
 9   Unnamed: 9       4 non-null      float64
dtypes: float64(4), int64(3), object(3)
memory usage: 39.2+ KB

In [36]:
df.describe()

,USER_ID,MOVIE_ID,PRODUCTION_YEAR,RATING,Unnamed: 6,Unnamed: 7,Unnamed: 9
count,500.000000,5.000000e+02,500.000000,500.000000,0.0,2.000000,4.000000
mean,250.500000,2.082635e+06,2012.134000,7.046400,NaN,3.000000,5.750000
std,144.481833,1.677033e+06,8.629077,1.584471,NaN,2.828427,1.707825
min,1.000000,6.141800e+04,1967.000000,1.000000,NaN,1.000000,4.000000
25%,125.750000,1.012145e+06,2013.000000,6.000000,NaN,2.000000,4.750000
50%,250.500000,1.663202e+06,2015.000000,7.000000,NaN,3.000000,5.500000
75%,375.250000,2.713180e+06,2017.000000,8.000000,NaN,4.000000,6.500000
max,500.000000,9.541602e+06,2019.000000,10.000000,NaN,5.000000,8.000000

In [37]:
df.shape

(500, 10)

In [38]:
df.shape[0]

500

In [39]:
df.shape[1]

10

In [40]:
df.size

5000

In [5]:
df.sample()

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
456,457,4779682,The Meg,2018,Action|Horror|Sci-Fi|Thriller,6.0,NaN,NaN,NaN,NaN

# access in column with loc and iloc

In [42]:
#loc

In [43]:
df.loc[0]

USER_ID                  1
MOVIE_ID           4642044
MOVIE_TITLE          Riot
PRODUCTION_YEAR       2015
GENRES              Action
RATING                 8.0
Unnamed: 6             NaN
Unnamed: 7             1.0
GENRES.1            action
Unnamed: 9             8.0
Name: 0, dtype: object

In [44]:
df.loc[[5,1,8]]

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
5,6,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5.0,NaN,NaN,NaN,NaN
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
8,9,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,10.0,NaN,NaN,NaN,NaN

In [45]:
df.loc[5,"MOVIE_TITLE"]

'Adrift '

In [91]:
df.loc[1:10,"MOVIE_TITLE"]

1             The Protector 2
2               Batman Begins
3     In the Heart of the Sea
4                      Adrift
5                      Adrift
6                     Everest
7                 Rescue Dawn
8                The Revenant
9                The Revenant
10               The Revenant
Name: MOVIE_TITLE, dtype: object

In [47]:
df.loc[1:10,["MOVIE_ID","MOVIE_TITLE","PRODUCTION_YEAR","GENRES","RATING"]]

,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
1,1925518,The Protector 2,2013,Action,5.0
2,372784,Batman Begins,2005,Action|Adventure,9.0
3,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0
4,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0
5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5.0
6,2719848,Everest,2015,Action|Adventure|Biography|Drama|Thriller,6.0
7,462504,Rescue Dawn,2006,Action|Adventure|Biography|Drama|War,8.0
8,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,10.0
9,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9.0
10,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9.2

In [48]:
x = df.loc[:,["MOVIE_ID","MOVIE_TITLE","PRODUCTION_YEAR","GENRES","RATING"]]
x

,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,4642044,Riot,2015,Action,8.0
1,1925518,The Protector 2,2013,Action,5.0
2,372784,Batman Begins,2005,Action|Adventure,9.0
3,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0
4,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0
...,...,...,...,...,...
495,1846589,Hunter Killer,2018,Action|Thriller,6.0
496,4196776,Jason Bourne,2016,Action|Thriller,6.0
497,7456310,Anna,2019,Action|Thriller,7.0
498,8106534,6 Underground,2019,Action|Thriller,4.0
499,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0

In [49]:
#iloc

In [8]:
df.iloc[0]

USER_ID                  1
MOVIE_ID           4642044
MOVIE_TITLE          Riot
PRODUCTION_YEAR       2015
GENRES              Action
RATING                 8.0
Unnamed: 6             NaN
Unnamed: 7             1.0
GENRES.1            action
Unnamed: 9             8.0
Name: 0, dtype: object

In [7]:
df.iloc[[0]]

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0

In [93]:
df.iloc[[0,1]]

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0

In [53]:
df.iloc[:,0]   # only in iloc

0        1
1        2
2        3
3        4
4        5
      ...
495    496
496    497
497    498
498    499
499    500
Name: USER_ID, Length: 500, dtype: int64

In [54]:
df.iloc[0:11,0:6]

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0
5,6,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,5.0
6,7,2719848,Everest,2015,Action|Adventure|Biography|Drama|Thriller,6.0
7,8,462504,Rescue Dawn,2006,Action|Adventure|Biography|Drama|War,8.0
8,9,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,10.0
9,10,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9.0
10,11,1663202,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9.2

In [55]:
df.iloc[0,2]="Roit 2"
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Roit 2,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN

In [56]:
df.iloc[8:15,[1,7,3]]

    MOVIE_ID  Unnamed: 7  PRODUCTION_YEAR
8    1663202         NaN             2015
9    1663202         NaN             2015
10   1663202         NaN             2015
11   1663202         NaN             2015
12   1663202         NaN             2015
13   1663202         NaN             2015
14   1663202         NaN             2015

In [57]:
df.iloc[8:35:3,::2]

,USER_ID,MOVIE_TITLE,GENRES,Unnamed: 6,GENRES.1
8,9,The Revenant,Action|Adventure|Biography|Drama|Western,NaN,NaN
11,12,The Revenant,Action|Adventure|Biography|Drama|Western,NaN,NaN
14,15,The Revenant,Action|Adventure|Biography|Drama|Western,NaN,NaN
17,18,The Man from U.N.C.L.E.,Action|Adventure|Comedy,NaN,NaN
20,21,The Man from U.N.C.L.E.,Action|Adventure|Comedy,NaN,NaN
23,24,Now You See Me 2,Action|Adventure|Comedy|Crime|Mystery|Thriller,NaN,NaN
26,27,Grimsby,Action|Adventure|Comedy|Crime|Thriller,NaN,NaN
29,30,Shazam!,Action|Adventure|Comedy|Fantasy,NaN,NaN
32,33,Shazam!,Action|Adventure|Comedy|Fantasy,NaN,NaN

# set_option for rows and column

In [58]:
# pd.set_option("display.max_rows",500)
# pd.set_option("display.max_rows",None) 
# pd.set_option("display.min_rows",5)
# pd.set_option("display.max_column",6)
# pd.set_option("display.max_colwidth",None)
# pd.reset_option("display.max_colwidth")
# pd.reset_option("display.width")

In [59]:
df = pd.read_csv(path)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING,Unnamed: 6,Unnamed: 7,GENRES.1,Unnamed: 9
0,1,4642044,Riot,2015,Action,8.0,NaN,1.0,action,8.0
1,2,1925518,The Protector 2,2013,Action,5.0,NaN,5.0,suspense,6.0
2,3,372784,Batman Begins,2005,Action|Adventure,9.0,NaN,NaN,drama,5.0
3,4,1390411,In the Heart of the Sea,2015,Action|Adventure|Biography|Drama|History|Thriller,5.0,NaN,NaN,thriller,4.0
4,5,6306064,Adrift,2018,Action|Adventure|Biography|Drama|Romance|Thriller,4.0,NaN,NaN,adventures,NaN
...,...,...,...,...,...,...,...,...,...,...
495,496,1846589,Hunter Killer,2018,Action|Thriller,6.0,NaN,NaN,NaN,NaN
496,497,4196776,Jason Bourne,2016,Action|Thriller,6.0,NaN,NaN,NaN,NaN
497,498,7456310,Anna,2019,Action|Thriller,7.0,NaN,NaN,NaN,NaN
498,499,8106534,6 Underground,2019,Action|Thriller,4.0,NaN,NaN,NaN,NaN
499,500,2302755,Olympus Has Fallen,2013,Action|Thriller,1.0,NaN,NaN,NaN,NaN